// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa-IdqBQ6f3d_SQI4HyD3hUOFE4YvGyiQ',
    appId: '1:205585638904:ios:20cc490490001dd579620d',
    messagingSenderId: '205585638904',
    projectId: 'estatebridge-app1',
    storageBucket: 'estatebridge-app1.firebasestorage.app',
    iosBundleId: 'com.example.estateBridge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVah2NSv8AX8KFhTt8IbcfGh4p4P8XReY',
    appId: '1:205585638904:web:7025f9ae56fc58d579620d',
    messagingSenderId: '205585638904',
    projectId: 'estatebridge-app1',
    authDomain: 'estatebridge-app1.firebaseapp.com',
    storageBucket: 'estatebridge-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-IdqBQ6f3d_SQI4HyD3hUOFE4YvGyiQ',
    appId: '1:205585638904:ios:20cc490490001dd579620d',
    messagingSenderId: '205585638904',
    projectId: 'estatebridge-app1',
    storageBucket: 'estatebridge-app1.firebasestorage.app',
    iosBundleId: 'com.example.estateBridge',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCalDalH0ufG-GeNJYI_-o7dE8UWUTlGg0',
    appId: '1:205585638904:android:d6b40b71e7913cc879620d',
    messagingSenderId: '205585638904',
    projectId: 'estatebridge-app1',
    storageBucket: 'estatebridge-app1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVah2NSv8AX8KFhTt8IbcfGh4p4P8XReY',
    appId: '1:205585638904:web:b5db63c197f361b679620d',
    messagingSenderId: '205585638904',
    projectId: 'estatebridge-app1',
    authDomain: 'estatebridge-app1.firebaseapp.com',
    storageBucket: 'estatebridge-app1.firebasestorage.app',
  );

}